#!/usr/bin/env bash

function handle {
  command=${1%>>*}
  data=${1#*>>}
  mode=$2
  if [[ $command == "workspace" && $mode == "active" ]]; then
    echo $data
  fi
  if [[ $command == "createworkspace" && $mode == "list" ]]; then
    workspaces=$(eww -c . get workspaces | jq -c --argjson v $data '[.[], $v] | sort_by(-.)')
    echo $workspaces
  fi
  if [[ $command == "destroyworkspace" && $mode == "list" ]]; then
    workspaces=$(eww -c . get workspaces | jq -c --argjson v $data '. | map(select(. != $v))')
    echo $workspaces
  fi
}

socat -u "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - | while read -r line; do handle "$line" $1; done
